### ISSUE TITLE
Implement `Drop` for `WindowEventHook`

### ISSUE THREAD

**Issue by Stefanuk12** [OpenByteDev/wineventhook-rs#1]
Developers may forget to call `.unhook()`. Implementing `Drop` on `WindowEventHook` can avoid this common pitfall.

**Comment by OpenByteDev** [comment]
Its not really required to call `.unhook()` as the hook will be cleared if the `abort_tx` is signaled, which happens when calling `.unhook()`, or if it is dropped, which happens when the `WinEventHook` is dropped even without a custom `Drop` implementation.

**Comment by OpenByteDev** [comment]
The reason `.unhook()` exists is just to make errors from the hook background thread visible.
